### ISSUE TITLE
[Conflict] No LightSaber in Hand

### ISSUE THREAD

**Issue by Peekofwar** [Blu-x92/lscs_public#11]
I encountered an issue where everything in the addon seemed to work flawlessly except the lightsabers would not appear in my hands. My character would act like he does, but I wouldn't be able to damage anything with attacks.

I went through 25 pages of addons disabling entire pages at a time to make searching for the conflict easier, and eventually came across what in my case was causing the conflict: [Manual Weapon Pickup](https://steamcommunity.com/sharedfiles/filedetails/?id=167545348). When only disabling this addon, and then loading into a new game, the lightsabers properly appear and work.

**Comment by Blu-x92** [comment]
this must be fixed from Manual Weapon Pickup-Addon's side. I don't see how i can fix it from my side.
