### ISSUE TITLE
All force powers except Force Lightning and Force Sense will not add to inventory.

### ISSUE THREAD

**Issue by RizzKingBrook** [Blu-x92/lscs_public#14]
All Force powers other than the ones mentioned will not add to LSCS inventory. When spawned in-game all other force item entities will not pick up. Console commands will not add them to inventory, they will instead just spawn once give item_force_— input is put in. I assumed this was a confliction with something like Vmanip but this is not a confliction issue as I have already tested this with just LSCS enabled and the same issue occurs. I don’t know much about Gmod Lua and coding but this might be a problem with the chromium branch or something or other. Don’t feel rushed to respond :)

**Comment by Blu-x92** [comment]
probably a third-party addon overwriting the default force powers. It's not possible for 'some' forcepowers to not work.
