### ISSUE TITLE
"Force" box entities breaking other addons' rendering code

### ISSUE THREAD

**Issue by parar020100** [Blu-x92/lscs_public#18]
It looks like you are not resetting the render material back to its previous value after using it 

`render.SetMaterial` should always get the current value and set it back to that after you're done but they're not doing that here

(looks like the issue starts in this file here: https://github.com/Blu-x92/lscs_public/blob/28768cf14fcf56bd75acfb2d39457fc2465c8074/lua/entities/lscs_force_base.lua#L38)

Here's an example of how it can affect other addons:
https://github.com/MattJeanes/TARDIS/issues/930

Video:
https://youtu.be/tmLLJOrwnFg

P.S. thank you for the mod, it is absolutely incredible!

**Comment by Blu-x92** [comment]
if this is whats breaking tardis, the issue is on tardis side for not calling render.SetMaterial before doing his render stuff. There is a million addons out there that do exactly the same as i do it is common practise
