### ISSUE TITLE
Inventory not preserved during reconnection/reboot

### ISSUE THREAD

**Issue by RavenTm7** [Blu-x92/lscs_public#22]
I recently started developing my own Gmod server with the idea of ​​making a SWTOR. The problem is that with each reconnection or reboot of the server, elements such as sleeves, crystals or combat forms have disappeared, which is quite restrictive to play quietly with a small community.

I downloaded the 4 basic LSCS addons and a few extensions and I don't know if I should put the Github content in the /addons folder on my server because it produces a lot of errors.

In the hope of having a fairly simple procedure to apply and some advice if possible in order to be able to use this addon as best as possible. I wish you a pleasant day and thank you in advance.

**Comment by Blu-x92** [comment]
please read https://github.com/Blu-x92/lscs_public/blob/main/zz_templates_and_info/how_to_save_and_restore_inventory.lua

**Comment by RavenTm7** [comment]
I understand but I don't know how to code that.

**Comment by RavenTm7** [comment]
![Screenshot_2024-01-26_12-13-04](https://github.com/Blu-x92/lscs_public/assets/157765504/673e40bd-13a6-4497-b808-fee58469cd21)

**Comment by Blu-x92** [comment]
please read the first 2 lines

**Comment by RavenTm7** [comment]
Already saw this file but Idk what to do with it. I'm not a Lua coder or anything like that

**Comment by RavenTm7** [comment]
Do I have to copy/paste it in a new file in lua/lscs/content ? So how do I call it ?

**Comment by RavenTm7** [comment]
The problem is resolved but I also got this : 

![image](https://github.com/Blu-x92/lscs_public/assets/157765504/f2dc25ca-6358-4986-b826-62e74f5ff131)

**Comment by Blu-x92** [comment]
cant you just use the workshop version?

**Comment by RavenTm7** [comment]
The problem is that the workshop version doesn't offer inventory save option

**Comment by RavenTm7** [comment]
So it's useless

**Comment by Blu-x92** [comment]
??? you dont have to extract the addon in order to use that lua file

**Comment by RavenTm7** [comment]
I trying it actually

**Comment by RavenTm7** [comment]
I worked thank you !
